import { query } from '../db';
import fs from 'fs';
import path from 'path';
import { getDbTomorrowStats } from '../db-tomorrow-stats';
import { getPrize1TomorrowStats } from '../prize1-tomorrow-stats';
import { calculateLoGan, calculateFrequent } from '../statistics';
import { analyzeLotoRoi } from '../loto-roi';

export class ArticleInputBuilder {
    static async buildContext(targetDate: string, yesterdayResult: any) {
        // 1. Read Optimized Bac Nho Files (Stats generated by calculating-bac-nho.ts)
        const bacNhoData = this.readBacNhoFiles();

        // 2. Head/Tail Statistics (Thống kê đầu đuôi) based on recent results
        // We can reuse calculateFrequent but group by head/tail
        // Or simplified: Just use 'frequencies' from existing stats logic if available.
        // Actually the user asked for "thống kê loto ( thống kê đầu đít )".
        // Let's implement a quick helper for this using recently fetched results.
        const headTailStats = await this.calculateHeadTailStats(30);

        // 3. Tomorrow Stats (Db & Prize 1)
        // Requires the "Target Number" - usually the last 2 digits of yesterday's Special & Prize 1
        if (!yesterdayResult || !yesterdayResult.special_prize || !yesterdayResult.prize_1) {
            throw new Error('Yesterday result data is incomplete - missing special_prize or prize_1');
        }

        const specialLoto = yesterdayResult.special_prize.slice(-2);
        const prize1Loto = yesterdayResult.prize_1.slice(-2);

        const [dbTomorrow, prize1Tomorrow, loGan, frequentLoto, lotoRoi] = await Promise.all([
            getDbTomorrowStats(specialLoto),
            getPrize1TomorrowStats(prize1Loto),
            calculateLoGan(10, 100),
            calculateFrequent(10, 30),
            analyzeLotoRoi(targetDate).catch(() => null)
        ]);

        return {
            targetDate,
            yesterdayResult,
            bacNho: bacNhoData,
            statistics: {
                headTail: headTailStats,
                loGan,
                frequentLoto,
                dbTomorrow: this.summarizeTomorrowStats(dbTomorrow),
                prize1Tomorrow: this.summarizeTomorrowStats(prize1Tomorrow),
                lotoRoi: this.summarizeLotoRoi(lotoRoi)
            }
        };
    }

    private static readBacNhoFiles() {
        const dataDir = path.join(process.cwd(), 'src', 'data');
        const readJson = (name: string) => {
            try {
                const content = fs.readFileSync(path.join(dataDir, `bac-nho-${name}.json`), 'utf-8');
                const json = JSON.parse(content);
                // Return top 5 predictions from 'todayPredictions'
                return json.data.todayPredictions?.slice(0, 5) || [];
            } catch (e) { return []; }
        };

        return {
            soDon: readJson('so-don'),
            cap2: readJson('cap-2'),
            cap3: readJson('cap-3'),
            haiNgay: readJson('2-ngay'),
            khung3Ngay: {
                soDon: readJson('khung-3-ngay-so-don'),
                cap2: readJson('khung-3-ngay-cap-2'),
                cap3: readJson('khung-3-ngay-cap-3'),
                haiNgay: readJson('khung-3-ngay-2-ngay')
            }
        };
    }

    private static async calculateHeadTailStats(days: number) {
        // Fetch last N days
        const rows = await query<any[]>(`SELECT * FROM xsmb_results ORDER BY draw_date DESC LIMIT ?`, [days]);
        const heads: Record<string, number> = {};
        const tails: Record<string, number> = {};

        rows.forEach(row => {
            const process = (val: string) => {
                if (!val || val.length < 2) return;
                const loto = val.slice(-2);
                if (!isNaN(Number(loto))) {
                    heads[loto[0]] = (heads[loto[0]] || 0) + 1;
                    tails[loto[1]] = (tails[loto[1]] || 0) + 1;
                }
            };
            // Process basic prizes for Head/Tail stats (usually just Special prize is most important, but user asked "thống kê loto")
            // Let's do ALL lotos for a general overview
            process(row.special_prize);
            process(row.prize_1);
            // ... (others if needed, but usually head/tail overview is fine with these)
        });

        // Sort
        const sortObj = (obj: Record<string, number>) => Object.entries(obj)
            .sort(([, a], [, b]) => b - a)
            .slice(0, 5) // Top 5
            .map(([k, v]) => `${k} (${v})`);

        return {
            topHeads: sortObj(heads),
            topTails: sortObj(tails)
        };
    }

    private static summarizeTomorrowStats(stats: any) {
        if (!stats) return null;
        return {
            target: stats.targetNumber,
            topFrequencies: stats.frequencies.slice(0, 5).map((f: any) => f.number),
            topHeads: stats.heads.slice(0, 3).map((f: any) => f.number),
            topTails: stats.tails.slice(0, 3).map((f: any) => f.number),
            topSums: stats.sums.slice(0, 3).map((f: any) => f.number)
        };
    }

    private static summarizeLotoRoi(stats: any) {
        if (!stats) return null;
        return {
            pair: stats.typeA?.pair,
            status: stats.typeA?.status,
            dbRoi: stats.typeB?.intersection?.numbers
        };
    }
}
